### ISSUE TITLE
repeated terms in autocomplete drop-down??

### ISSUE THREAD

**Issue by austinmeier** [Planteome/planteome-table-editor#7]
When using the sheet to fill a new trait in, typing "plant" will return a drop-down menu for autocompleted ontology terms via OLS API (I think??)  For some reason, when searching for terms, it repeats the most likely result a number of times (between 4-10 times).  This reduces the overall number of results to pick from, and can be confusing for users.

**Comment by austinmeier** [comment]
Needs to restrict the config for accessing OLS.

@cmungall

**Comment by cooperl09** [comment]
I'm closing, as this appears to be resolved.
